I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/be1.rpy", line 27, in script
    with Shake((0, 0, 0, 0), 3.0, dist=30)
  File "game/be1.rpy", line 27, in <module>
    with Shake((0, 0, 0, 0), 3.0, dist=30)
NameError: name 'Shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/be1.rpy", line 27, in script
    with Shake((0, 0, 0, 0), 3.0, dist=30)
  File "renpy/ast.py", line 1436, in execute
    trans = renpy.python.py_eval(self.expr)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/be1.rpy", line 27, in <module>
    with Shake((0, 0, 0, 0), 3.0, dist=30)
NameError: name 'Shake' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Da Capo 1.0
Tue Jan  4 23:21:15 2022
