I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ch1.rpy", line 70, in script
    show cello eye with fade(0.2, 0.0, 0.8, color="#fff")
  File "game/ch1.rpy", line 70, in <module>
    show cello eye with fade(0.2, 0.0, 0.8, color="#fff")
TypeError: Fade() got multiple values for keyword argument 'color'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ch1.rpy", line 70, in script
    show cello eye with fade(0.2, 0.0, 0.8, color="#fff")
  File "renpy/ast.py", line 1439, in execute
    paired = renpy.python.py_eval(self.paired)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/ch1.rpy", line 70, in <module>
    show cello eye with fade(0.2, 0.0, 0.8, color="#fff")
  File "renpy/curry.py", line 48, in __call__
    return self.callable(*(self.args + args), **merged_kwargs)
TypeError: Fade() got multiple values for keyword argument 'color'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Da Capo 1.0
Wed Jan  5 19:15:31 2022
