I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ch1.rpy", line 32, in script
    q_c "......你覺得這幅景象很美嗎？"
Exception: Sayer 'q_c' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ch1.rpy", line 32, in script
    q_c "......你覺得這幅景象很美嗎？"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'q_c' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Da Capo 1.0
Tue Jan  4 16:14:07 2022
